name: backend CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          secrets: |
            "github_token=${{ secrets.SECRET_TOKEN }}"
          push: true
          tags: wan2da/repeller-server:latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          sync: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u 'wan2da' -p 'QKRwodhks1!!@' docker.io
            docker pull wan2da/repeller-server:latest
            docker stop repeller-server
            docker rm repeller-server
            docker run -d --name 'repeller-server' -p 8080:8080 wan2da/repeller-server:latest
